version: 2.1

orbs:
  vro: kohirens/version-release@2

parameters:
  secrets:
    default: kohirens-automation
    description: Secrets context
    type: string
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "4f:88:2a:81:b5:1c:47:5e:68:24:ae:d3:3a:54:95:06"
  triggered_by_bot:
    default: false
    description: Trigger publishing a release tag workflow.
    type: boolean

executors:
  def:
    docker:
      - image: cimg/go:1.20

jobs:
  co:
    executor: def
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths: [ . ]

  run-test:
    executor: def
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Unit test"
          command: |
            go test -v

workflows:
  pull-request:
    jobs:
      - co
      - run-test:
          requires: [ co ]

  publish-changelog:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [webhook, << pipeline.trigger_source >>]
    jobs:
      - vro/publish-changelog:
          context: << pipeline.parameters.secrets >>
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - << pipeline.parameters.triggered_by_bot >>
    jobs:
      - vro/tag-and-release:
          context: << pipeline.parameters.secrets >>
